### ISSUE TITLE
FreeCAD-0.21.0dev-31391 closes without showing UI - Illegal storage access

### ISSUE THREAD

**Issue by casterle** [FreeCAD/FreeCAD-Bundle#148]
Windows 11 x64 Pro,

0.20.1 runs fine, as does the weekly build version 30922 (11/10/22). Weekly builds thereafter do not run correctly. 

Today I tried again, using FreeCAD-0.21.0dev-31391-Installer.exe. I found out how to turn on logging, and found this at the end of the log file:

Log: Init: Showing main window
Log: Main window restored
Err: Illegal storage access...
Log: Destruct Gui::Application
Err: <Exception> Illegal storage access! Please save your work under a new file name and restart the application!

Crash.log is empty.

**Comment by luzpaz** [comment]
Always add your Full [About](https://wiki.freecadweb.org/About) info

**Comment by casterle** [comment]
> Always add your Full [About](https://wiki.freecadweb.org/About) info

How can I do that if the program never presents the UI?

**Comment by luzpaz** [comment]
From the CLI you can run: `path\to\FreeCAD.exe --version --verbose`

**Comment by casterle** [comment]
> From the CLI you can run: `path\to\FreeCAD.exe --version --verbose`

Thanks, here's what I get:

```
FreeCAD 0.21.0 Revision: 31391 (Git)

Library versions:
boost    1_67
Coin3D   4.0.1
Eigen3   3.3.90
OCC      7.6.3
Qt       5.15.2
Python   3.8.10
PySide   5.15.0
shiboken 5.15.0
SMESH    7.7.1.0
VTK      8.2.0
xerces-c 3.2.2
```

**Comment by tre4b** [comment]
@casterle How does this manifest for you?   Do you run FreeCAD and nothing happens?

I ask because this is what I am experiencing with the 31391 installer build and what I was looking here for support for.  This is the first time I have installed an installer build. Fortunately it installed in a different location to 31097, which still works for me.

I have tried copying the files from the install like I would have done previously, but it still does not work at all.  If this is different to your issue then I will create a new issue.

**Comment by casterle** [comment]
> @casterle How does this manifest for you? Do you run FreeCAD and nothing happens?
> 
> I ask because this is what I am experiencing with the 31391 installer build and what I was looking here for support for. This is the first time I have installed an installer build. Fortunately it installed in a different location to 31097, which still works for me.
> 
> I have tried copying the files from the install like I would have done previously, but it still does not work at all. If this is different to your issue then I will create a new issue

The problem, it turned out, was something in my user.cfg file. I deleted the file and found that the UI came up as expected. I was unable to determine which entry in the file was causing the problem.

I hope this works for you.

It would be nice if pre-release versions used a different config file.

**Comment by luzpaz** [comment]
> It would be nice if pre-release versions used a different config file.

@wwmayer what are your thoughts on this idea since user.cfg corruption is quite common and usually doesn't get fixed (users are told to backup and move config files)

**Comment by tre4b** [comment]
@casterle -  Many thanks, I deleted user.cfg and it all works perfectly for me now as well.  So something that has changed slightly in the file I would guess.  I kept a copy of it in case I could help figure out which bit causes this.  It is quite likely that it is something fairly specific to our personal installations and thus rarely encountrered.

**Comment by casterle** [comment]
> I deleted user.cfg and it all works perfectly for me now as well.

I'm glad I was able to help.

**Comment by adrianinsaval** [comment]
is this issue solved then? please close if that is the case, note also that if this is not a strictly packaging related problem it's best to report at the main repository github.com/FreeCAD/FreeCAD since this repository deals strictly with generating packages for distribution

**Comment by luzpaz** [comment]
This is another usecase for the https://github.com/FreeCAD/FreeCAD/issues/6106

**Comment by wwmayer** [comment]
@luzpaz I don't think that the user.cfg files are anyhow corrupted in terms of the XML structure is invalid because in this case the parsing would fail and the application would start with an empty parameter set -- just like if there were no user.cfg at all.

The problem must rather be that there are parameters that cause a crash because the component  that reads their values doesn't verify them.
