### ISSUE TITLE
[Problem] Windows weekly not building

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD-Bundle#330]
@adrianinsaval the Windows weekly build failed. Also manually starting the job resulted in an error.

**Comment by oursland** [comment]
This appears to be an issue due to incompatible dependencies.  It should be resolved through the use of lock files.

Such lock file management is automated through `pixi`, but the current development of `pixi` using the same `conda-forge` dependencies results in a strange build failure on Windows that neither @looooo nor I understand: https://github.com/oursland/FreeCAD/actions/runs/11656954868/job/32453798456

**Comment by maxwxyz** [comment]
Seems to work again

**Comment by adrianinsaval** [comment]
I had to remove opencv so it could solve dependencies. It is not used in freecad itself so I think that's fine. I know assembly 4 used it but I think that doesn't work in 1.0 anyways
